apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ template "fullname" . }}
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer
